# Generated by Django 5.0.1 on 2024-01-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('level', models.FloatField(max_length=15, null=True)),
                ('view', models.IntegerField(max_length=15, null=True)),
                ('hard', models.IntegerField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('adress', models.CharField(max_length=100, null=True)),
                ('level', models.FloatField(max_length=15, null=True)),
                ('view', models.IntegerField(max_length=15, null=True)),
                ('hard', models.IntegerField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('lastname', models.CharField(max_length=20, null=True)),
                ('firstname', models.CharField(max_length=25, null=True)),
                ('middlename', models.CharField(max_length=25, null=True)),
                ('specialty', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=25, null=True)),
                ('experience', models.IntegerField(null=True)),
                ('consultation_price', models.IntegerField(null=True)),
                ('office', models.CharField(max_length=100, null=True)),
                ('working_days', models.CharField(max_length=25, null=True)),
                ('time', models.IntegerField(null=True)),
                ('phone', models.IntegerField(max_length=25, null=True)),
                ('bio', models.TextField()),
                ('level', models.FloatField(max_length=15, null=True)),
                ('view', models.IntegerField(max_length=15, null=True)),
                ('hard', models.IntegerField(max_length=15, null=True)),
            ],
        ),
    ]
