# Generated by Django 5.0.1 on 2024-02-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('icon', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='hospitals',
            name='type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='web_site',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pharmacys',
            name='type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='pharmacys',
            name='web_site',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
