# Generated by Django 5.0.2 on 2024-02-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_section_hospitals_type_hospitals_web_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='hard',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='view',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pharmacys',
            name='hard',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacys',
            name='view',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='hard',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='view',
            field=models.IntegerField(null=True),
        ),
    ]
