# Generated by Django 5.0.2 on 2024-02-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_hospitals_hard_alter_hospitals_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='type',
            field=models.CharField(blank=True, choices=[('davlat', 'Davlat'), ('hususiy', 'Hususiy')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacys',
            name='type',
            field=models.CharField(blank=True, choices=[('davlat', 'Davlat'), ('hususiy', 'Hususiy')], max_length=30, null=True),
        ),
    ]
