# Generated by Django 5.0.2 on 2024-02-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_specialist_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='time',
        ),
        migrations.AddField(
            model_name='specialist',
            name='begin_time',
            field=models.CharField(choices=[('00:00', '00:00'), ('01:00', '01:00'), ('02:00', '02:00'), ('03:00', '03:00'), ('04:00', '04:00'), ('05:00', '05:00'), ('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='end_time',
            field=models.CharField(choices=[('00:00', '00:00'), ('01:00', '01:00'), ('02:00', '02:00'), ('03:00', '03:00'), ('04:00', '04:00'), ('05:00', '05:00'), ('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialty',
            field=models.CharField(blank=True, choices=[('lor', 'Lor'), ('jarroh', 'Jarroh'), ('urolog', 'Urolog'), ('genekolog', 'Genekolog'), ('akusher', 'Akusher'), ('Allergolog', 'Allergolog'), ('Androlog', 'Androlog'), ('Anesteziolog', 'Anesteziolog'), ('Venerolog', 'Venerolog'), ('Virusolog', 'Virusolog'), ('Dermatolog', 'Dermatolog'), ('Dietolog', 'Dietolog'), ('Kardiolog', 'Kardiolog'), ('Logoped', 'Logoped'), ('Mammolog', 'Mammolog'), ('Narkolog', 'Narkolog'), ('Nevropatolog', 'Nevropatolog'), ('Nefrolog', 'Nefrolog'), ('Oftalmolog', 'Oftalmolog'), ('Onkolog', 'Onkolog'), ('Ortoped', 'Ortoped'), ('Otorinolaringolog', 'Otorinolaringolog'), ('Pediatr', 'Pediatr'), ('Podolog', 'Podolog'), ('Proktolog', 'Proktolog'), ('Psixiatr', 'Psixiatr'), ('Psixoterapevt', 'Psixoterapevt'), ('Pulmanolog', 'Pulmanolog'), ('Ftiziatr', 'Ftiziatr'), ('Reanimatolog', 'Reanimatolog'), ('Terapevt', 'Terapevt'), ('Travmatolog', 'Travmatolog'), ('Endokrinolog', 'Endokrinolog'), ('Kosmetolog', 'Kosmetolog'), ('Stomatolog', 'Stomatolog')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='working_days',
            field=models.CharField(blank=True, choices=[('Dushanba-Juma', 'Dushanba-Juma'), ('Dushanba-Shanba', 'Dushanba-Shanba'), ('Dushanba-Chorshanba-Juma', 'Dushanba-Chorshanba-Juma'), ('Seshanba-Payshanba-Shanba', 'Seshanba-Payshanba-Shanba'), ('Xar kuni', 'Xar kuni')], max_length=25, null=True),
        ),
    ]
