# Generated by Django 5.0.2 on 2024-02-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('Terapiya', 'Terapiya'), ('Lor', 'Lor'), ('Reanimatsiya', 'Reanimatsiya'), ('Tramatologiya', 'Tramatologiya'), ('Hirurgiya', 'Hirurgiya'), ('Genekologiya', 'Genekologiya'), ('Urologiya', 'Urologiya'), ('uqumli_kasalliklar', 'Yuqumli Kasalliklar'), ('Onkologiya', 'Onkologiya'), ('Bolalar', 'Bolalar'), ('Gematologiya', 'Gematologiya')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialty',
            field=models.CharField(blank=True, choices=[('lor', 'Lor'), ('jarroh', 'Jarroh'), ('urolog', 'Urolog'), ('genekolog', 'Genekolog'), ('akusher', 'Akusher'), ('Allergolog', 'Allergolog'), ('Androlog', 'Androlog'), ('Anesteziolog', 'Anesteziolog'), ('Venerolog', 'Venerolog'), ('Virusolog', 'Virusolog'), ('Dermatolog', 'Dermatolog'), ('Dietolog', 'Dietolog'), ('Kardiolog', 'Kardiolog'), ('Logoped', 'Logoped'), ('Mammolog', 'Mammolog'), ('Narkolog', 'Narkolog'), ('Nevropatolog', 'Nevropatolog'), ('Nefrolog', 'Nefrolog'), ('Oftalmolog', 'Oftalmolog'), ('Infeksionist', 'Infeksionist'), ('Onkolog', 'Onkolog'), ('Ortoped', 'Ortoped'), ('Otorinolaringolog', 'Otorinolaringolog'), ('Pediatr', 'Pediatr'), ('Podolog', 'Podolog'), ('Proktolog', 'Proktolog'), ('Psixiatr', 'Psixiatr'), ('Psixoterapevt', 'Psixoterapevt'), ('Pulmanolog', 'Pulmanolog'), ('Ftiziatr', 'Ftiziatr'), ('Reanimatolog', 'Reanimatolog'), ('Terapevt', 'Terapevt'), ('Travmatolog', 'Travmatolog'), ('Endokrinolog', 'Endokrinolog'), ('Kosmetolog', 'Kosmetolog'), ('Stomatolog', 'Stomatolog'), ('Gematolog', 'Gematolog')], max_length=100, null=True),
        ),
    ]
