from django.test import TestCase

# Create your tests here.
LOR = 'lor'                 
JARROH = 'jarroh'
UROLOG = 'urolog'
GENEKOLOG = 'genekolog'
AKUSHER = 'akusher'
Allergolog = 'Allergolog'
Venerolog = 'Venerolog'
Virusolog = 'Virusolog'
Dermatolog = 'Dermatolog'
Dietolog = 'Dietolog'
Kardiolog = 'Kardiolog'
Logoped = 'Logoped'
Mammolog = 'Mammolog'
Narkolog = 'Narkolog'
Nevropatolog = 'Nevropatolog'
Nefrolog = 'Nefrolog'
Oftalmolog = 'Oftalmolog'
Infeksionist = 'Infeksionist'
Onkolog = 'Onkolog'
Ortoped = 'Ortoped'
Otorinolaringolog = 'Otorinolaringolog'
Pediatr = 'Pediatr'
Podolog  = 'Podolog'
Proktolog = 'Proktolog'
Psixiatr = 'Psixiatr'
Psixoterapevt = 'Psixoterapevt'
Pulmanolog = 'Pulmanolog'
Ftiziatr = 'Ftiziatr'
Reanimatolog = 'Reanimatolog'
Terapevt = 'Terapevt'
Travmatolog = 'Travmatolog'
Endokrinolog = 'Endokrinolog'
Kosmetolog = 'Kosmetolog'
Stomatolog = 'Stomatolog'
Gematolog = 'Gematolog'